测试用例数量：73

1. 失败的测试用例数量：5
失败的测试用例：
testCaseTea.test_text.TestTextFunc.test_word_2
Traceback (most recent call last):
  File "..\testCaseTea\test_text.py", line 18, in test_word_2
    self.assertListEqual(li,[('tara', 11), ('arabic', 6), ('women', 5), ('esl', 5), ('each', 5), ('students', 4), ('rose', 4), ('other', 4), ('iraq', 4), ('day', 4)])
AssertionError: Lists differ: [('tara', 11), ('"', 8), ('arabic', 6), ('women', 5), ('es[71 chars], 4)] != [('tara', 11), ('arabic', 6), ('women', 5), ('esl', 5), ('[74 chars], 4)]

First differing element 1:
('"', 8)
('arabic', 6)

  [('tara', 11),
-  ('"', 8),
   ('arabic', 6),
   ('women', 5),
   ('esl', 5),
   ('each', 5),
   ('students', 4),
+  ('rose', 4),
   ('other', 4),
   ('iraq', 4),
   ('day', 4)]

testCaseTea.test_text.TestTextFunc.test_word_3
Traceback (most recent call last):
  File "..\testCaseTea\test_text.py", line 22, in test_word_3
    self.assertListEqual(li,[('hacker', 78), ('hackers', 61), ('learn', 37), ('―', 33), ('source', 30), ('other', 28), ('software', 26), ('linux', 26), ('most', 25), ('culture', 25)])
AssertionError: Lists differ: [('hacker', 72), ('hackers', 56), ('learn', 37), ('―',[93 chars] 24)] != [('hacker', 78), ('hackers', 61), ('learn', 37), ('―',[95 chars] 25)]

First differing element 0:
('hacker', 72)
('hacker', 78)

- [('hacker', 72),
?              ^

+ [('hacker', 78),
?              ^

-  ('hackers', 56),
?              -

+  ('hackers', 61),
?               +

   ('learn', 37),
   ('―', 33),
-  ('source', 28),
?             ^^

+  ('source', 30),
?             ^^

   ('other', 28),
+  ('software', 26),
+  ('linux', 26),
   ('most', 25),
-  ('linux', 25),
-  ('culture', 25),
?                 ^

+  ('culture', 25)]
?                 ^

-  ('things', 24)]

testCaseTea.test_data.TestXmlFunc.test_db_3
Traceback (most recent call last):
  File "..\testCaseTea\test_data.py", line 107, in test_db_3
    self.assertEquals(get_total_salary(),2)
AssertionError: 10000 != 2

testCaseTea.test_data.TestXmlFunc.test_db_4
Traceback (most recent call last):
  File "..\testCaseTea\test_data.py", line 122, in test_db_4
    self.assertEquals(get_total_salary(),2)
AssertionError: 10000 != 2

testCaseTea.test_net.TestNetFunc.test_net_2
Traceback (most recent call last):
  File "..\testCaseTea\test_net.py", line 21, in test_net_2
    self.assertIn('益阳',citys.keys())
AssertionError: '益阳' not found in dict_keys(['长沙'])


2. 错误的测试用例数量：0

3. 通过的测试用例数量：68

总分80分，最后得分：75